import type { Package } from '../types'

export const caribbeanCoast: Package = {
  slug: "caribbean-coast",
  name: "Caribbean Coast: Santa Marta, Palomino & La Guajira",
  title: "Colombia's Caribbean Coast: Santa Marta, Tayrona, Palomino & La Guajira",
  metaDescription: "Nine nights along Colombia's Caribbean coast — Minca cloud forest, Tayrona, the Palomino river, and the desert of La Guajira. From $5,200 per person.",
  nights: 9,
  days: 10,
  priceFrom: 5200,
  cities: ["Santa Marta", "Minca", "Tayrona", "Palomino", "La Guajira"],
  featured: false,
  heroImage: "/packages/caribbean-coast/hero.jpg",
  gallery: [],
  summary: "The full length of Colombia's northern coast, ending in the desert where the continent runs out. This is the trip for people who've already done Cartagena and want the version with far fewer other Americans in it.",
  itinerary: [
    { day: 1, title: "Arrival in Santa Marta — the centre after dark", body: "Private transfer from the airport, then the historic centre in the evening — Parque de los Novios, street food, and the coast's own rhythm, which is slower than Cartagena's and better for it." },
    { day: 2, title: "Up to Minca", body: "An hour into the Sierra Nevada. Waterfalls, coffee, cooler air." },
    { day: 3, title: "Minca", body: "Birding at dawn if you want it, hammocks if you don't." },
    { day: 4, title: "Tayrona National Park", body: "Down to the coast and into the park. Cabo San Juan and the jungle walk in." },
    { day: 5, title: "To Palomino", body: "Two hours east. Tubing down the river from the mountains to the sea, which sounds gimmicky and isn't." },
    { day: 6, title: "Palomino", body: "Beach, and the emptiest stretch of sand on this coast. Nothing scheduled." },
    { day: 7, title: "Into La Guajira", body: "Four hours into the desert. Cabo de la Vela — dunes running straight into the Caribbean, Wayuu communities, and a landscape that looks like a different continent." },
    { day: 8, title: "La Guajira", body: "Punta Gallinas, the northernmost point of South America, if the roads allow. This is 4x4 country and the day is long." },
    { day: 9, title: "Back west", body: "Return towards Santa Marta or Riohacha, breaking the drive." },
    { day: 10, title: "Departure", body: "Private transfer to Santa Marta or Riohacha airport." },
  ],
  included: [
    "9 nights accommodation across the coast",
    "All private ground transfers including 4x4 for La Guajira",
    "Minca waterfalls and coffee finca",
    "Tayrona National Park entry and guide",
    "Palomino river tubing",
    "La Guajira desert expedition with local guide",
    "24/7 phone access while you are in Colombia",
  ],
  excluded: [
    "International and domestic flights",
    "Travel insurance",
    "Meals not listed",
    "Tayrona is subject to seasonal closure — see below",
  ],
  hotels: [
    { name: "Masaya Santa Marta — Centro Histórico", city: "Santa Marta", why: "Old centre, pool, walkable." },
    { name: "Minca Luxury Cabins — Deluxe Bungalow", city: "Minca", why: "The view is the room. Take the deluxe." },
    { name: "Palomino Cabin Style Ocean Front", city: "Palomino", why: "Directly on the sand. Simple, and exactly right for where it is." },
    { name: "La Guajira Boutique Hotel", city: "La Guajira", why: "The best available out there, which is a real sentence and not a hedge — this is remote country and standards drop. I'd rather say so." },
  ],
  caveat: "La Guajira is the least developed place I take anyone. The roads are unpaved, the accommodation is basic by design, and Punta Gallinas depends on conditions. It is also the most extraordinary landscape in Colombia. If basic accommodation for two nights would ruin your trip, tell me and I'll end the itinerary at Palomino.",
}
