import type { Package } from '../types'

export const cartagenaCoffeeRegion: Package = {
  slug: "cartagena-coffee-region",
  name: "Cartagena & the Coffee Region",
  title: "Cartagena & the Coffee Region: Caribbean Coast to Coffee Country",
  metaDescription: "Eight nights pairing Cartagena's walled city and the Rosario Islands with Colombia's coffee country — Salento, Cocora Valley and working farms. From $4,700 per person.",
  nights: 8,
  days: 9,
  priceFrom: 4700,
  cities: ["Cartagena", "Rosario Islands", "Salento", "Cocora Valley"],
  featured: false,
  heroImage: "/packages/cartagena-coffee-region/hero.jpg",
  gallery: [],
  summary: "Heat and cool, sea and mountain. Cartagena is the Colombia people arrive expecting; the coffee region is the one they leave talking about. The contrast between the two halves is the entire argument for this itinerary.",
  itinerary: [
    { day: 1, title: "Arrival in Cartagena — sunset and the first night out", body: "Private transfer, fifteen minutes from the airport. Sunset on the walls, then Getsemaní after dark — rum tasting or a salsa class, your call. Cartagena earns its reputation at night." },
    { day: 2, title: "Walled city and Getsemaní", body: "Private guide in the morning, Getsemaní and its street art in the afternoon, evening free." },
    { day: 3, title: "Rosario Islands", body: "Full day out on the water with lunch on the island." },
    { day: 4, title: "Cartagena free day", body: "Food tour, beach, or the emerald workshop. Sunset catamaran in the evening." },
    { day: 5, title: "Fly to the coffee region", body: "Cartagena to Pereira via Bogotá or Medellín, then a private transfer to Salento. The long travel day of the trip — I schedule it deliberately in the middle rather than at either end." },
    { day: 6, title: "Cocora Valley", body: "Early for the wax palms. Afternoon free." },
    { day: 7, title: "Coffee and chocolate farms", body: "Private farm visits, the full process, with the people who run it." },
    { day: 8, title: "Filandia and the hot springs", body: "Filandia's mirador in the morning, Santa Rosa thermal pools in the afternoon. The best last full day of any trip I run." },
    { day: 9, title: "Departure", body: "Private transfer to Pereira or Armenia." },
  ],
  included: [
    "8 nights accommodation across Cartagena and Salento",
    "All private ground transfers including airport runs",
    "Arrival-night rum tasting or salsa class in Getsemaní",
    "Private walled city tour and Getsemaní walk",
    "Full-day Rosario Islands boat trip with lunch",
    "Sunset catamaran experience",
    "Private Cocora Valley experience",
    "Coffee and chocolate farm experiences",
    "Filandia day and Santa Rosa hot springs",
    "24/7 phone access while you are in Colombia",
  ],
  excluded: [
    "International flights",
    "Domestic flight Cartagena to the coffee region (I book it, you pay cost — usually $90–160 per person)",
    "Travel insurance",
    "Meals not listed",
  ],
  hotels: [
    { name: "Townhouse Boutique Hotel & Rooftop", city: "Cartagena", why: "Inside the walls, small, with the rooftop you'll use every night." },
    { name: "Salento Hotel", city: "Salento", why: "In town, quiet, walkable." },
    { name: "GHL Hotel Abadía Plaza", city: "Pereira", why: "Only if flight times force an airport night. Functional." },
  ],
  caveat: "The Cartagena–Pereira leg almost always connects through Bogotá or Medellín, so it eats most of a day. If you'd rather not lose it, tell me and I'll swap the coffee region for Santa Marta, which is a four-hour drive instead of a flight.",
}
