import type { Package } from '../types'

export const colombiaHighlights: Package = {
  slug: "colombia-highlights",
  name: "Colombia Highlights: Medellín, Coffee Region & Cartagena",
  title: "Colombia Highlights: Medellín, Coffee Country & Cartagena in 11 Nights",
  metaDescription: "Eleven nights across Colombia's three essential regions — Medellín and Guatapé, the coffee country and Cocora Valley, and Cartagena's walled city and islands. From $6,400 per person.",
  nights: 11,
  days: 12,
  priceFrom: 6400,
  cities: ["Medellín", "Guatapé", "Salento", "Cocora Valley", "Cartagena", "Rosario Islands"],
  featured: true,
  heroImage: "/packages/colombia-highlights/hero.jpg",
  gallery: [],
  summary: "The complete trip. Three regions, each with enough time to stop feeling like a tour — a real city, real coffee country, and the Caribbean. Twelve days is the point where Colombia stops being a highlights reel and starts being a country you know something about.",
  itinerary: [
    { day: 1, title: "Arrival in Medellín — the city at night", body: "Private transfer from the airport. Evening: the 360 miradores run, the valley lit from every side. It asks nothing of you after a long flight and it orients you completely." },
    { day: 2, title: "Comuna 13 and the city", body: "Private guide through the neighbourhood and the viewpoints." },
    { day: 3, title: "Coffee farm and free afternoon", body: "A working farm outside the city; the afternoon is yours." },
    { day: 4, title: "Guatapé", body: "Two hours out. El Peñol late in the day, the town in the evening." },
    { day: 5, title: "Guatapé lake day", body: "Free day on the water." },
    { day: 6, title: "Fly to the coffee region", body: "Back to Medellín, short flight to Pereira or Armenia, transfer to Salento." },
    { day: 7, title: "Cocora Valley", body: "Early for the wax palms. Afternoon free in Salento." },
    { day: 8, title: "Coffee and chocolate farms", body: "The private farm experience, then Filandia in the afternoon." },
    { day: 9, title: "Fly to Cartagena", body: "Travel day north. Afternoon arrival, sunset on the walls." },
    { day: 10, title: "Walled city and Getsemaní", body: "Private guide in the morning, street art in the afternoon." },
    { day: 11, title: "Rosario Islands", body: "Full day out on the water with lunch." },
    { day: 12, title: "Departure", body: "Sunset catamaran the evening before if timings allow; private transfer to the airport." },
  ],
  included: [
    "11 nights accommodation across three regions",
    "All private ground transfers including both airport runs",
    "Evening 360 miradores city-lights tour on arrival night",
    "Private Comuna 13 and Medellín city tour",
    "Two working farm experiences",
    "Guatapé day with El Peñol and lake boat",
    "Private Cocora Valley experience",
    "Filandia and miradores day",
    "Arrival-night rum tasting or salsa class in Getsemaní",
    "Private walled city tour and Getsemaní walk",
    "Full-day Rosario Islands trip with lunch",
    "Sunset catamaran experience",
    "24/7 phone access while you are in Colombia",
  ],
  excluded: [
    "International flights",
    "Two domestic flights (I book them, you pay cost — usually $150–250 per person total)",
    "Travel insurance",
    "Meals not listed",
  ],
  hotels: [
    { name: "Celestino Boutique Hotel & Spa", city: "Medellín", why: "Quiet side of Provenza, small enough to feel personal." },
    { name: "Hotel & Spa Guatapé", city: "Guatapé", why: "Lake views and a pool." },
    { name: "Salento Hotel", city: "Salento", why: "In town, walkable, quiet at night." },
    { name: "Townhouse Boutique Hotel & Rooftop", city: "Cartagena", why: "Inside the walls, with the rooftop." },
  ],
  caveat: "Two domestic flights means two mornings partly lost to airports. That's the honest cost of covering three regions, and it's why I don't sell this itinerary in under eleven nights. If you have fewer days, take Medellín and Cartagena and leave the coffee region for next time — and there usually is a next time.",
}
