import type { Package } from '../types'

export const medellinCartagena: Package = {
  slug: "medellin-cartagena",
  name: "Medellín & Cartagena",
  title: "Medellín & Cartagena: Colombia's Two Essential Cities in 8 Nights",
  metaDescription: "Eight nights across Medellín and Cartagena — Comuna 13, Guatapé, the walled city and the Rosario Islands, all with private guides. From $4,800 per person.",
  nights: 8,
  days: 9,
  priceFrom: 4800,
  cities: ["Medellín", "Guatapé", "Cartagena", "Rosario Islands"],
  featured: true,
  heroImage: "/packages/medellin-cartagena/hero.jpg",
  gallery: [],
  summary: "If you only do one Colombia trip, this is it. The two cities are nothing like each other — one is a valley city rebuilt out of a genuinely dark thirty years, the other is a Caribbean port that's looked much the same since the 1600s. A short flight between them and no wasted days.",
  itinerary: [
    { day: 1, title: "Arrival in Medellín — the city at night", body: "Private transfer from the airport. Evening: the 360 miradores run — the whole valley lit up, which is how you should meet this city. Nothing strenuous on arrival day." },
    { day: 2, title: "Comuna 13 and the city", body: "Private guide, the neighbourhood, the viewpoints, the history." },
    { day: 3, title: "Coffee farm day", body: "A working farm outside the city, afternoon free for paragliding or the cable car." },
    { day: 4, title: "Guatapé", body: "Out to the lake, El Peñol, and the town in the evening. One night out here." },
    { day: 5, title: "Fly to Cartagena", body: "Back to Medellín and a one-hour flight north. Afternoon arrival, sunset on the walls." },
    { day: 6, title: "Walled city and Getsemaní", body: "Private guide in the morning, street art and the neighbourhood in the afternoon." },
    { day: 7, title: "Rosario Islands", body: "Full day on the water, lunch on the island." },
    { day: 8, title: "Cartagena free day", body: "Food tour, beach or workshops, then the sunset catamaran." },
    { day: 9, title: "Departure", body: "Private transfer to Cartagena airport." },
  ],
  included: [
    "8 nights accommodation across Medellín, Guatapé and Cartagena",
    "All private ground transfers including both airport runs",
    "Evening 360 miradores city-lights tour on arrival night",
    "Private Comuna 13 and Medellín city tour",
    "Coffee farm experience",
    "Guatapé day with El Peñol and lake boat",
    "Arrival-night rum tasting or salsa class in Getsemaní",
    "Private walled city tour and Getsemaní walk",
    "Full-day Rosario Islands trip with lunch",
    "Sunset catamaran experience",
    "24/7 phone access while you are in Colombia",
  ],
  excluded: [
    "International flights",
    "Domestic flight Medellín to Cartagena (I book it, you pay cost — usually $70–130 per person)",
    "Travel insurance",
    "Meals not listed",
  ],
  hotels: [
    { name: "Celestino Boutique Hotel & Spa", city: "Medellín", why: "Provenza, quiet side, small." },
    { name: "Hotel & Spa Guatapé", city: "Guatapé", why: "Lake views, pool, away from the square." },
    { name: "Townhouse Boutique Hotel & Rooftop", city: "Cartagena", why: "Walled city, rooftop, my default for couples." },
  ],
  caveat: "Nine days is right for this itinerary and eight is not — I've tried it and the Guatapé night gets cut, which is the wrong thing to lose. If you only have eight, I'd drop Guatapé entirely rather than compress it.",
}
