import type { Package } from '../types'

export const medellinCoffeeRegion: Package = {
  slug: "medellin-coffee-region",
  name: "Medellín & the Coffee Region",
  title: "Medellín & the Coffee Region: 8 Nights of City, Lake & Coffee Country",
  metaDescription: "Eight nights combining Medellín, Guatapé and Colombia's coffee country — private guides, working farms, the Cocora Valley wax palms. From $4,600 per person.",
  nights: 8,
  days: 9,
  priceFrom: 4600,
  cities: ["Medellín", "Guatapé", "Salento", "Cocora Valley"],
  featured: true,
  heroImage: "/packages/medellin-coffee-region/hero.jpg",
  gallery: [],
  summary: "The two regions that pair best. Medellín gives you a real city with a difficult, fascinating recent history; the coffee region gives you the green, slow counterweight an hour's flight south. Nine days is the shortest trip where neither half feels rushed.",
  itinerary: [
    { day: 1, title: "Arrival in Medellín — the city at night", body: "Private transfer from the airport, roughly 45 minutes. Evening: the 360 miradores run, Medellín lit up from every side of the valley. Low effort after a long flight and the best possible orientation to a city built on a slope." },
    { day: 2, title: "Comuna 13 and the city", body: "Private guide through Comuna 13 and the city viewpoints. The history here is recent enough that the people telling it lived through it, which is the whole reason to do this with a guide." },
    { day: 3, title: "Coffee farm and free afternoon", body: "A working farm outside the city, then the afternoon free. Paragliding, chocolate tour or the Arví Park cable car if you want to fill it." },
    { day: 4, title: "To Guatapé", body: "Two hours out to the lake. El Peñol in the afternoon when the tour buses have thinned, then the town in the evening." },
    { day: 5, title: "Guatapé lake day", body: "Free day on the water. Boat, swim, or sit." },
    { day: 6, title: "Fly south to the coffee region", body: "Back to Medellín and a short flight to Pereira or Armenia, then a private transfer to Salento. Travel day, but a short one." },
    { day: 7, title: "Cocora Valley", body: "Early start for the wax palms before the cloud arrives. Afternoon free in Salento." },
    { day: 8, title: "Coffee and chocolate farms", body: "The private farm experience — properly, with the family that runs it. Afternoon in Filandia for the mirador and a slower town." },
    { day: 9, title: "Departure", body: "Private transfer to Pereira or Armenia for your flight out." },
  ],
  included: [
    "8 nights accommodation across Medellín, Guatapé and Salento",
    "All private ground transfers including airport runs",
    "Evening 360 miradores city-lights tour on arrival night",
    "Private Comuna 13 and Medellín city tour",
    "Two working farm experiences — coffee near Medellín, coffee and chocolate in Salento",
    "Guatapé day with El Peñol and lake boat",
    "Private Cocora Valley experience",
    "Filandia and miradores day",
    "24/7 phone access while you are in Colombia",
  ],
  excluded: [
    "International flights",
    "Domestic flight Medellín to Pereira or Armenia (I book it, you pay cost — usually $60–110 per person)",
    "Travel insurance",
    "Meals not listed",
  ],
  hotels: [
    { name: "Celestino Boutique Hotel & Spa", city: "Medellín", why: "Quiet corner of Provenza, small enough that the staff learn your name in two days." },
    { name: "Hotel & Spa Guatapé", city: "Guatapé", why: "Lake views and a pool, away from the weekend noise of the town square." },
    { name: "Salento Hotel", city: "Salento", why: "Walkable to Calle Real and quiet at night." },
  ],
  caveat: "The internal flight is the one moving part in this trip. Colombian domestic carriers change schedules with little notice, so I build a buffer day around it and I don't book your international return tight against it. If a flight moves, I move the trip — that's what the 24/7 number is for.",
}
